### ISSUE TITLE
mac是不是不能用啊

### ISSUE THREAD

**Issue by weil-Leslie** [LittleBear4/Find-SomeThing#5]
/bin/sh: observer_ward.exe: command not found
Traceback (most recent call last):
  File "/Find-SomeThing/scan.py", line 14, in <module>
    console.entrance()
  File "/Find-SomeThing/main/console.py", line 35, in entrance
    frame.API2(url)
  File "/Find-SomeThing/main/frame.py", line 53, in API2
    content=deal.frameDataDeal(data)
  File "/Find-SomeThing/main/deal.py", line 61, in frameDataDeal
    vulnerabilities=str(data[3])
IndexError: list index out of range

**Comment by LittleBear4** [comment]
是的 暂时没有写mac版本的
