### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Nightingle-yeying** [LittleBear4/Find-SomeThing#7]
系统找不到指定的路径。
'observer_ward.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

Traceback (most recent call last):
  File "D:\work\t00ls\t00ls\python-tools\Find-SomeThing-main\scan.py", line 14, in <module>
    console.entrance()
  File "D:\work\t00ls\t00ls\python-tools\Find-SomeThing-main\main\console.py", line 46, in entrance
    frame.install()
  File "D:\work\t00ls\t00ls\python-tools\Find-SomeThing-main\main\frame.py", line 66, in install
    print(data[10])
          ~~~~^^^^
IndexError: list index out of range

**Comment by shanxigetanxiaochou** [comment]
+1

**Comment by scvjx** [comment]
因为文件路径有中文导致
